### ISSUE TITLE
x2goagent nightly crashes with Composite but without render

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#163]
Running on Ubuntu 14.04

```
gdb -ex "handle SIGHUP nostop" -ex "set height 0" -ex "run -ac +extension Composite -norender :55" /usr/lib/nx/../x2go/bin/x2goagent
```

(or simply `/usr/bin/x1goagent -ac +extension Composite -norender :55` if you do not want the backtrace)

leads to

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000043b85b in ?? ()
(gdb) bt
#0  0x000000000043b85b in ?? ()
#1  0x00000000005027b2 in ?? ()
#2  0x000000000044d557 in ?? ()
#3  0x000000000080cce8 in ?? ()
#4  0x0000000000806760 in ?? ()
#5  0x00000000004a268d in ?? ()
#6  0x000000000045f1ed in ?? ()
#7  0x000000000049e06f in ?? ()
#8  0x000000000040e88a in ?? ()
#9  0x00007ffff5696ec5 in __libc_start_main (main=0x40e680, argc=6, 
    argv=0x7fffffffdf68, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdf58) at libc-start.c:287
#10 0x000000000040ef38 in ?? ()
```

If I remove  `-norender` it works.

**Comment by sunweaver** [comment]
@HolySephi: I think that this issue can be closed now. Relevant commits / PRs: https://github.com/ArcticaProject/nx-libs/commit/dd5f5b56b48127641ca2bf70a272f60872f2568b (#172) and https://github.com/ArcticaProject/nx-libs/commit/5b36f6443a1186d482ae1044b826c9fd67624c31 (#170).

Thus, closing. Reopen if issue re-occurs.
