### ISSUE TITLE
Segmentation fault in ProcGetProperty

### ISSUE THREAD

**Issue by opoplawski** [ArcticaProject/nx-libs#305]
With 3.5.99.3 on ScientificLinux 7.2
```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f004fd232b4 in ProcGetProperty (client=0x7f0051972f50) at NXproperty.c:371
371         pProp = wUserProps (pWin);
(gdb) print *pWin
$2 = {drawable = {type = 0 '\000', class = 12 '\f', depth = 57 '9', bitsPerPixel = 61 '=',
    id = 4285059833871677, x = 15616, y = -1, width = 65535, height = 65535,
    pScreen = 0x4affffffffffff, serialNumber = 18446744073709502464}, parent = 0x4dffffffffffff,
  nextSib = 0xffffffffffff4000, prevSib = 0x4dffffffffffff, firstChild = 0xffffffffffff4000,
  lastChild = 0x4dffffffffffff, clipList = {extents = {x1 = 16384, y1 = -1, x2 = -1, y2 = -1},
    data = 0x4dffffffffffff}, borderClip = {extents = {x1 = 16384, y1 = -1, x2 = -1, y2 = -1},
    data = 0x4dffffffffffff}, valdata = 0xffffffffffff4000, winSize = {extents = {x1 = -1,
      y1 = -1, x2 = -1, y2 = 77}, data = 0xffffffffffff4000}, borderSize = {extents = {x1 = -1,
      y1 = -1, x2 = -1, y2 = 77}, data = 0xffffffffffff4000}, origin = {x = -1, y = -1},
  borderWidth = 65534, deliverableEvents = 52, eventMask = 4294918144, background = {
    pixmap = 0x278fffeffffff, pixel = 695990843604991}, border = {pixmap = 0xffffffffffff4000,
    pixel = 18446744073709502464}, backStorage = 0x380fffeffff, optional = 0xffffffffffff4000,
  backgroundState = 3, borderIsPixel = 1, cursorIsNone = 1, backingStore = 3, saveUnder = 1,
  DIXsaveUnder = 1, bitGravity = 14, winGravity = 15, overrideRedirect = 1, visibility = 3,
  mapped = 1, realized = 1, viewable = 1, dontPropagate = 7, forcedBS = 1, redirectDraw = 1,
  devPrivates = 0xffffffffffff4000}
(gdb) print pProp
$3 = <optimized out>
(gdb) print pWin->optional
$4 = (WindowOptPtr) 0xffffffffffff4000
(gdb) print *pWin->optional
Cannot access memory at address 0xffffffffffff4000
(gdb) bt
#0  0x00007f004fd232b4 in ProcGetProperty (client=0x7f0051972f50) at NXproperty.c:371
#1  0x00007f004fd2fd1c in Dispatch () at NXdispatch.c:491
#2  0x00007f004fd12dcb in main (argc=17, argv=0x7ffe9890c8e8, envp=<optimized out>) at main.c:433

**Comment by sunweaver** [comment]
@opoplawski: can you provide more info on what this happens? Does the segfault happen at session start? Or does it occur after some specific actions in the running X session? Or does it happen arbitrarily?

**Comment by uli42** [comment]
I am confident that #338 fixes this. 

@opoplawski can you please test?

**Comment by sunweaver** [comment]
@uli42: shall we close this one with regards to the merge of #338, as well?

**Comment by uli42** [comment]
yes, I close it, this is a garbled Window (==Drawable) as well.
