### ISSUE TITLE
double free

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#833]
In 3.5.99.21:

1. nxagent -ac :55
2. pkill -HUP nxagent
3. pkill -HUP nxagent
4. close NX window via close button

-> Result:
```
free(): double free detected in tcache 2

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6478535 in __GI_abort () at abort.c:79
#2  0x00007ffff64cf508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff65da28d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff64d5c1a in malloc_printerr (str=str@entry=0x7ffff65dbf58 "free(): double free detected in tcache 2") at malloc.c:5341
#4  0x00007ffff64d76fd in _int_free (av=0x7ffff6611c40 <main_arena>, p=0x555555cc2050, have_lock=<optimized out>) at malloc.c:4193
#5  0x0000555555953b82 in RRCloseScreen (pScreen=0x555555b73f40) at randr.c:139
#6  0x0000555555686f4f in CursorCloseScreen (pScreen=0x555555b73f40) at cursor.c:170
#7  0x0000555555963ec0 in AnimCurCloseScreen (pScreen=<optimized out>) at animcur.c:128
#8  0x0000555555599ec3 in main (argc=3, argv=0x7fffffffdd58, envp=<optimized out>) at main.c:382
```

**Comment by uli42** [comment]
This commit introduced the problem: 3b06ad51d91ff2b9442f159cddf34ed03bc2dd35

**Comment by uli42** [comment]
I have added the revert of the above commit to pr/various2. However, this comes at the price of re-introducing a memleak.
