### ISSUE TITLE
Crash in RegionDestroy

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#909]
In my test-Version I saw this crash today. This version contains the pr/various4 PR.

```
#0  RegionDestroy (pReg=0x0) at region.c:341
#1  0x00000000007ebf90 in miSetShape (pWin=0xccfa320) at miwindow.c:1063
#2  0x00000000004fb223 in RegionOperate (pWin=pWin@entry=0xccfa320, kind=0, destRgnp=0x72fdf48, srcRgn=<optimized out>, srcRgn@entry=0x2bdd870, op=<optimized out>, xoff=0, yoff=0, 
    create=create@entry=0x4fa790 <CreateBoundingShape>, client=0x29d1e90) at shape.c:260
#3  0x00000000004fb445 in ProcShapeRectangles (client=0x29d1e90) at shape.c:382
#4  0x00000000004fbfed in ProcShapeDispatch (client=0x29d1e90) at shape.c:1126
#5  0x0000000000431b13 in Dispatch () at NXdispatch.c:488
#6  0x000000000040f15a in main (argc=20, argv=0x7ffeccfc12d8, envp=<optimized out>) at main.c:350
```

**Comment by uli42** [comment]
Oh, I had totally forgotten this. See #926 and #927 for a fix
