### ISSUE TITLE
Unresponsive session

### ISSUE THREAD

**Issue by uli42** [ArcticaProject/nx-libs#970]
Today my session got stuck while I was doing something outside the session. When activating the session window again it was not responsive. It was displaying the Centos unlock screen.

I attached a debugger and set SleepTimeMillis to 0 but this had no effect. It seems nxagent starves due to lots of Xrender requests:
```
#0  0x00007f7dd2ba9983 in __select_nocancel () from /lib64/libc.so.6
#1  0x00007f7dd564fe5e in NXTransSelect (resultFDs=resultFDs@entry=0x7ffdeda47088, errorFDs=errorFDs@entry=0x7ffdeda4708c, setFDs=setFDs@entry=0x7ffdeda47084, readSet=readSet@entry=0x7ffdeda47200, 
    writeSet=writeSet@entry=0x7ffdeda47120, selectTs=selectTs@entry=0x7f7dd5c389f0 <retry>) at Loop.cpp:2742
#2  0x00007f7dd593c7bc in _XSelect (maxfds=<optimized out>, readfds=readfds@entry=0x7ffdeda47200, writefds=0x7ffdeda47120, writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, 
    timeout=0x7f7dd5c389f0 <retry>) at XlibInt.c:303
#3  0x00007f7dd593e130 in _XWaitForReadable (dpy=dpy@entry=0x2eb69020) at XlibInt.c:755
#4  0x00007f7dd593e3e0 in _XRead (dpy=dpy@entry=0x2eb69020, data=data@entry=0x7ffdeda47380 "\262V\f\t", size=size@entry=32) at XlibInt.c:1571
#5  0x00007f7dd593fda4 in _XReply (dpy=dpy@entry=0x2eb69020, rep=rep@entry=0x7ffdeda47380, extra=extra@entry=0, discard=discard@entry=1) at XlibInt.c:2211
#6  0x00007f7dd594087f in _XIDHandler (dpy=dpy@entry=0x2eb69020) at XlibInt.c:1982
#7  0x00007f7dd5940950 in _XPrivSyncFunction (dpy=0x2eb69020) at XlibInt.c:916
#8  0x00007f7dd51b9d09 in XRenderCreatePicture () from /lib64/libXrender.so.1
#9  0x00000000004a7595 in nxagentCreatePicture (pPicture=pPicture@entry=0x5a30da0, mask=<optimized out>) at Render.c:689
#10 0x0000000000436114 in ProcRenderCreatePicture (client=<optimized out>) at NXrender.c:425
#11 0x00000000004325f8 in xorg_ProcRenderDispatch (client=<optimized out>) at ../../mi/../render/render.c:2043
#12 ProcRenderDispatch (client=<optimized out>) at NXrender.c:1771
#13 0x0000000000431c03 in Dispatch () at NXdispatch.c:486
#14 0x000000000040f10a in main (argc=20, argv=0x7ffdeda477c8, envp=<optimized out>) at main.c:350
(gdb) c
```

**Comment by uli42** [comment]
Happened again:

```
#0  0x00007f3a3477aa13 in __select_nocancel () from /lib64/libc.so.6
#1  0x00007f3a37220e5e in NXTransSelect (resultFDs=resultFDs@entry=0x7ffcf4bc5da8, errorFDs=errorFDs@entry=0x7ffcf4bc5dac, setFDs=setFDs@entry=0x7ffcf4bc5da4, readSet=readSet@entry=0x7ffcf4bc5f20, 
    writeSet=writeSet@entry=0x7ffcf4bc5e40, selectTs=selectTs@entry=0x7f3a378099f0 <retry>) at Loop.cpp:2742
#2  0x00007f3a3750d7fc in _XSelect (maxfds=<optimized out>, readfds=readfds@entry=0x7ffcf4bc5f20, writefds=0x7ffcf4bc5e40, writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=0x7f3a378099f0 <retry>) at XlibInt.c:303
#3  0x00007f3a3750f170 in _XWaitForReadable (dpy=dpy@entry=0x298a1b30) at XlibInt.c:755
#4  0x00007f3a3750f420 in _XRead (dpy=dpy@entry=0x298a1b30, data=data@entry=0x7ffcf4bc60a0 "", size=size@entry=32) at XlibInt.c:1571
#5  0x00007f3a37510de4 in _XReply (dpy=dpy@entry=0x298a1b30, rep=rep@entry=0x7ffcf4bc60a0, extra=extra@entry=0, discard=discard@entry=1) at XlibInt.c:2211
#6  0x00007f3a375118bf in _XIDHandler (dpy=dpy@entry=0x298a1b30) at XlibInt.c:1982
#7  0x00007f3a37511990 in _XPrivSyncFunction (dpy=0x298a1b30) at XlibInt.c:916
#8  0x00007f3a374eb799 in XCreateGC (dpy=0x298a1b30, d=117440555, valuemask=valuemask@entry=0, values=values@entry=0x0) at CrGC.c:100
#9  0x000000000048ce85 in nxagentCreateGC (pGC=0x29e94a0) at GC.c:170
#10 0x00000000007e0184 in miBSCreateGC (pGC=0x29e94a0) at mibstore.c:762
#11 0x00000000004f1b9b in damageCreateGC (pGC=0x29e94a0) at damage.c:358
#12 0x0000000000455e59 in CreateGC (pDrawable=pDrawable@entry=0x138d4c0, mask=0, pval=pval@entry=0x3512bb44, pStatus=pStatus@entry=0x7ffcf4bc6210) at gc.c:666
#13 0x000000000042bd86 in ProcCreateGC (client=0x1b21240) at ../../dix/dispatch.c:1552
#14 0x0000000000431cc3 in Dispatch () at NXdispatch.c:486
#15 0x000000000040f10a in main (argc=20, argv=0x7ffcf4bc6428, envp=<optimized out>) at main.c:350
```
